import { ConfidenceLevel, FoodType, PreparationState, ReferenceUnit } from '@prisma/client';

export const USDA_FDC_SOURCE_URL = 'https://fdc.nal.usda.gov/';

export const FOOD_CATEGORIES = [
  { code: 'EGGS', name: 'Huevos', displayOrder: 1 },
  { code: 'POULTRY', name: 'Aves', displayOrder: 2 },
  { code: 'MEAT', name: 'Carnes', displayOrder: 3 },
  { code: 'CEREALS', name: 'Cereales', displayOrder: 4 },
  { code: 'TUBERS', name: 'Tubérculos', displayOrder: 5 },
  { code: 'FATS', name: 'Grasas', displayOrder: 6 },
  { code: 'BAKERY', name: 'Panificados', displayOrder: 7 },
  { code: 'DAIRY', name: 'Lácteos', displayOrder: 8 },
  { code: 'BEVERAGES', name: 'Bebidas', displayOrder: 9 },
  { code: 'FRUITS', name: 'Frutas', displayOrder: 10 },
  { code: 'VEGETABLES', name: 'Vegetales', displayOrder: 11 },
  { code: 'CONDIMENTS', name: 'Condimentos', displayOrder: 12 },
] as const;

export const NUTRIENT_DEFINITIONS = [
  {
    code: 'ENERGY_KCAL',
    name: 'Energía',
    unit: 'kcal',
    group: 'ENERGY',
    displayOrder: 1,
    isRequired: true,
  },
  {
    code: 'PROTEIN',
    name: 'Proteína',
    unit: 'g',
    group: 'MACRONUTRIENT',
    displayOrder: 2,
    isRequired: true,
  },
  {
    code: 'CARBOHYDRATE',
    name: 'Carbohidratos',
    unit: 'g',
    group: 'MACRONUTRIENT',
    displayOrder: 3,
    isRequired: true,
  },
  {
    code: 'FAT',
    name: 'Grasas',
    unit: 'g',
    group: 'MACRONUTRIENT',
    displayOrder: 4,
    isRequired: true,
  },
  {
    code: 'FIBER',
    name: 'Fibra',
    unit: 'g',
    group: 'OTHER',
    displayOrder: 5,
    isRequired: false,
  },
  {
    code: 'SUGAR',
    name: 'Azúcares',
    unit: 'g',
    group: 'OTHER',
    displayOrder: 6,
    isRequired: false,
  },
  {
    code: 'SATURATED_FAT',
    name: 'Grasas saturadas',
    unit: 'g',
    group: 'OTHER',
    displayOrder: 7,
    isRequired: false,
  },
  {
    code: 'SODIUM',
    name: 'Sodio',
    unit: 'mg',
    group: 'MINERAL',
    displayOrder: 8,
    isRequired: false,
  },
  {
    code: 'CALCIUM',
    name: 'Calcio',
    unit: 'mg',
    group: 'MINERAL',
    displayOrder: 9,
    isRequired: false,
  },
  {
    code: 'IRON',
    name: 'Hierro',
    unit: 'mg',
    group: 'MINERAL',
    displayOrder: 10,
    isRequired: false,
  },
  {
    code: 'POTASSIUM',
    name: 'Potasio',
    unit: 'mg',
    group: 'MINERAL',
    displayOrder: 11,
    isRequired: false,
  },
  {
    code: 'MAGNESIUM',
    name: 'Magnesio',
    unit: 'mg',
    group: 'MINERAL',
    displayOrder: 12,
    isRequired: false,
  },
  {
    code: 'VITAMIN_C',
    name: 'Vitamina C',
    unit: 'mg',
    group: 'VITAMIN',
    displayOrder: 13,
    isRequired: false,
  },
  {
    code: 'VITAMIN_A',
    name: 'Vitamina A',
    unit: 'µg RAE',
    group: 'VITAMIN',
    displayOrder: 14,
    isRequired: false,
  },
] as const;

export type NutrientCode = (typeof NUTRIENT_DEFINITIONS)[number]['code'];

export interface FoodServingSeed {
  name: string;
  quantity: number;
  unit: string;
  equivalentGrams?: number;
  equivalentMilliliters?: number;
}

export interface NutritionCatalogFoodSeed {
  name: string;
  description: string;
  categoryCode: (typeof FOOD_CATEGORIES)[number]['code'];
  foodType: FoodType;
  preparationState: PreparationState;
  referenceQuantity: number;
  referenceUnit: ReferenceUnit;
  source: 'USDA_FDC_SR_LEGACY' | 'USDA_FDC_FNDDS_2021_2023' | 'LOCAL_SEED';
  sourceReference: string;
  confidenceLevel: ConfidenceLevel;
  nutrients: Record<NutrientCode, number>;
  servings?: FoodServingSeed[];
  aliases?: string[];
}

const globalFoodDefaults = {
  foodType: FoodType.GENERIC,
  referenceQuantity: 100,
  referenceUnit: ReferenceUnit.GRAM,
  confidenceLevel: ConfidenceLevel.VERIFIED,
} as const;

export const NUTRITION_CATALOG_FOODS: NutritionCatalogFoodSeed[] = [
  {
    ...globalFoodDefaults,
    name: 'Huevo entero crudo',
    description: 'USDA: Egg, whole, raw, fresh.',
    categoryCode: 'EGGS',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171287',
    nutrients: {
      ENERGY_KCAL: 143,
      PROTEIN: 12.6,
      CARBOHYDRATE: 0.72,
      FAT: 9.51,
      FIBER: 0,
      SUGAR: 0.37,
      SATURATED_FAT: 3.13,
      SODIUM: 142,
      CALCIUM: 56,
      IRON: 1.75,
      POTASSIUM: 138,
      MAGNESIUM: 12,
      VITAMIN_C: 0,
      VITAMIN_A: 160,
    },
    servings: [{ name: 'Huevo grande', quantity: 1, unit: 'UNIT', equivalentGrams: 50 }],
  },
  {
    ...globalFoodDefaults,
    name: 'Huevo entero cocido',
    description: 'USDA: Egg, whole, cooked, hard-boiled.',
    categoryCode: 'EGGS',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '173424',
    nutrients: {
      ENERGY_KCAL: 155,
      PROTEIN: 12.6,
      CARBOHYDRATE: 1.12,
      FAT: 10.6,
      FIBER: 0,
      SUGAR: 1.12,
      SATURATED_FAT: 3.27,
      SODIUM: 124,
      CALCIUM: 50,
      IRON: 1.19,
      POTASSIUM: 126,
      MAGNESIUM: 10,
      VITAMIN_C: 0,
      VITAMIN_A: 149,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Pechuga de pollo cruda',
    description: 'USDA: Chicken breast, skinless, boneless, meat only, raw.',
    categoryCode: 'POULTRY',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171077',
    nutrients: {
      ENERGY_KCAL: 120,
      PROTEIN: 22.5,
      CARBOHYDRATE: 0,
      FAT: 2.62,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 0.563,
      SODIUM: 45,
      CALCIUM: 5,
      IRON: 0.37,
      POTASSIUM: 334,
      MAGNESIUM: 28,
      VITAMIN_C: 0,
      VITAMIN_A: 9,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Pechuga de pollo cocida',
    description: 'USDA: Chicken breast, meat only, cooked, roasted.',
    categoryCode: 'POULTRY',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171477',
    nutrients: {
      ENERGY_KCAL: 165,
      PROTEIN: 31,
      CARBOHYDRATE: 0,
      FAT: 3.57,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 1.01,
      SODIUM: 74,
      CALCIUM: 15,
      IRON: 1.04,
      POTASSIUM: 256,
      MAGNESIUM: 29,
      VITAMIN_C: 0,
      VITAMIN_A: 6,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Carne vacuna magra cruda',
    description: 'USDA: Beef top round steak, separable lean only, raw.',
    categoryCode: 'MEAT',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171757',
    nutrients: {
      ENERGY_KCAL: 121,
      PROTEIN: 23.6,
      CARBOHYDRATE: 0,
      FAT: 2.94,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 1.12,
      SODIUM: 54,
      CALCIUM: 13,
      IRON: 2.34,
      POTASSIUM: 313,
      MAGNESIUM: 12,
      VITAMIN_C: 0,
      VITAMIN_A: 2,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Carne vacuna magra cocida',
    description: 'USDA: Beef top round steak, separable lean only, cooked, grilled.',
    categoryCode: 'MEAT',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '168649',
    nutrients: {
      ENERGY_KCAL: 162,
      PROTEIN: 30.1,
      CARBOHYDRATE: 0,
      FAT: 3.77,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 1.56,
      SODIUM: 75,
      CALCIUM: 18,
      IRON: 3.25,
      POTASSIUM: 435,
      MAGNESIUM: 17,
      VITAMIN_C: 0,
      VITAMIN_A: 3,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Carne molida cruda',
    description: 'USDA: Beef, ground, 90% lean meat / 10% fat, raw.',
    categoryCode: 'MEAT',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '174030',
    nutrients: {
      ENERGY_KCAL: 176,
      PROTEIN: 20,
      CARBOHYDRATE: 0,
      FAT: 10,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 3.93,
      SODIUM: 66,
      CALCIUM: 12,
      IRON: 2.24,
      POTASSIUM: 321,
      MAGNESIUM: 20,
      VITAMIN_C: 0,
      VITAMIN_A: 4,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Arroz blanco crudo',
    description: 'USDA: Rice, white, long-grain, regular, raw, unenriched.',
    categoryCode: 'CEREALS',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '169756',
    nutrients: {
      ENERGY_KCAL: 365,
      PROTEIN: 7.13,
      CARBOHYDRATE: 80,
      FAT: 0.66,
      FIBER: 1.3,
      SUGAR: 0.12,
      SATURATED_FAT: 0.18,
      SODIUM: 5,
      CALCIUM: 28,
      IRON: 0.8,
      POTASSIUM: 115,
      MAGNESIUM: 25,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Arroz blanco cocido',
    description: 'USDA: Rice, white, long-grain, regular, unenriched, cooked without salt.',
    categoryCode: 'CEREALS',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '169757',
    nutrients: {
      ENERGY_KCAL: 130,
      PROTEIN: 2.69,
      CARBOHYDRATE: 28.2,
      FAT: 0.28,
      FIBER: 0.4,
      SUGAR: 0.05,
      SATURATED_FAT: 0.077,
      SODIUM: 1,
      CALCIUM: 10,
      IRON: 0.2,
      POTASSIUM: 35,
      MAGNESIUM: 12,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Papa cruda',
    description: 'USDA: Potatoes, flesh and skin, raw.',
    categoryCode: 'TUBERS',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '170026',
    nutrients: {
      ENERGY_KCAL: 77,
      PROTEIN: 2.05,
      CARBOHYDRATE: 17.5,
      FAT: 0.09,
      FIBER: 2.1,
      SUGAR: 0.82,
      SATURATED_FAT: 0.025,
      SODIUM: 6,
      CALCIUM: 12,
      IRON: 0.81,
      POTASSIUM: 425,
      MAGNESIUM: 23,
      VITAMIN_C: 19.7,
      VITAMIN_A: 0,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Papa hervida',
    description: 'USDA: Potatoes, boiled, cooked without skin, flesh, without salt.',
    categoryCode: 'TUBERS',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '170440',
    nutrients: {
      ENERGY_KCAL: 86,
      PROTEIN: 1.71,
      CARBOHYDRATE: 20,
      FAT: 0.1,
      FIBER: 1.8,
      SUGAR: 0.89,
      SATURATED_FAT: 0.026,
      SODIUM: 5,
      CALCIUM: 8,
      IRON: 0.31,
      POTASSIUM: 328,
      MAGNESIUM: 20,
      VITAMIN_C: 7.4,
      VITAMIN_A: 0,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Papa al horno',
    description: 'USDA: Potatoes, baked, flesh and skin, without salt.',
    categoryCode: 'TUBERS',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '170093',
    nutrients: {
      ENERGY_KCAL: 93,
      PROTEIN: 2.5,
      CARBOHYDRATE: 21.2,
      FAT: 0.13,
      FIBER: 2.2,
      SUGAR: 1.18,
      SATURATED_FAT: 0.034,
      SODIUM: 10,
      CALCIUM: 15,
      IRON: 1.08,
      POTASSIUM: 535,
      MAGNESIUM: 28,
      VITAMIN_C: 9.6,
      VITAMIN_A: 1,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Yuca cruda',
    description: 'USDA: Cassava, raw.',
    categoryCode: 'TUBERS',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '169985',
    nutrients: {
      ENERGY_KCAL: 160,
      PROTEIN: 1.36,
      CARBOHYDRATE: 38.1,
      FAT: 0.28,
      FIBER: 1.8,
      SUGAR: 1.7,
      SATURATED_FAT: 0.074,
      SODIUM: 14,
      CALCIUM: 16,
      IRON: 0.27,
      POTASSIUM: 271,
      MAGNESIUM: 21,
      VITAMIN_C: 20.6,
      VITAMIN_A: 1,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Yuca hervida',
    description: 'USDA FNDDS: Cassava, cooked.',
    categoryCode: 'TUBERS',
    preparationState: PreparationState.COOKED,
    source: 'USDA_FDC_FNDDS_2021_2023',
    sourceReference: '2709564',
    nutrients: {
      ENERGY_KCAL: 191,
      PROTEIN: 1.42,
      CARBOHYDRATE: 39.6,
      FAT: 3.03,
      FIBER: 1.9,
      SUGAR: 1.78,
      SATURATED_FAT: 0.793,
      SODIUM: 145,
      CALCIUM: 17,
      IRON: 0.28,
      POTASSIUM: 282,
      MAGNESIUM: 22,
      VITAMIN_C: 18.2,
      VITAMIN_A: 13,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Aceite de oliva',
    description: 'USDA: Oil, olive, salad or cooking.',
    categoryCode: 'FATS',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171413',
    nutrients: {
      ENERGY_KCAL: 884,
      PROTEIN: 0,
      CARBOHYDRATE: 0,
      FAT: 100,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 13.8,
      SODIUM: 2,
      CALCIUM: 1,
      IRON: 0.56,
      POTASSIUM: 1,
      MAGNESIUM: 0,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
    servings: [
      { name: 'Cucharada', quantity: 1, unit: 'TABLESPOON', equivalentGrams: 13.5 },
      { name: 'Cucharadita', quantity: 1, unit: 'TEASPOON', equivalentGrams: 4.5 },
      { name: '3 ml', quantity: 3, unit: 'MILLILITER', equivalentGrams: 2.73 },
    ],
  },
  {
    ...globalFoodDefaults,
    name: 'Manteca',
    description: 'USDA: Butter, without salt.',
    categoryCode: 'FATS',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '173430',
    nutrients: {
      ENERGY_KCAL: 717,
      PROTEIN: 0.85,
      CARBOHYDRATE: 0.06,
      FAT: 81.1,
      FIBER: 0,
      SUGAR: 0.06,
      SATURATED_FAT: 50.5,
      SODIUM: 11,
      CALCIUM: 24,
      IRON: 0.02,
      POTASSIUM: 24,
      MAGNESIUM: 2,
      VITAMIN_C: 0,
      VITAMIN_A: 684,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Pan de sándwich genérico',
    description: 'USDA: Bread, white, commercially prepared.',
    categoryCode: 'BAKERY',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '174924',
    nutrients: {
      ENERGY_KCAL: 266,
      PROTEIN: 8.85,
      CARBOHYDRATE: 49.4,
      FAT: 3.33,
      FIBER: 2.7,
      SUGAR: 5.67,
      SATURATED_FAT: 0.698,
      SODIUM: 490,
      CALCIUM: 144,
      IRON: 3.61,
      POTASSIUM: 126,
      MAGNESIUM: 23,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
    servings: [{ name: 'Rebanada', quantity: 1, unit: 'SLICE', equivalentGrams: 25 }],
  },
  {
    ...globalFoodDefaults,
    name: 'Yogur natural',
    description: 'USDA: Yogurt, plain, whole milk.',
    categoryCode: 'DAIRY',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171284',
    nutrients: {
      ENERGY_KCAL: 61,
      PROTEIN: 3.47,
      CARBOHYDRATE: 4.66,
      FAT: 3.25,
      FIBER: 0,
      SUGAR: 4.66,
      SATURATED_FAT: 2.1,
      SODIUM: 46,
      CALCIUM: 121,
      IRON: 0.05,
      POTASSIUM: 155,
      MAGNESIUM: 12,
      VITAMIN_C: 0.5,
      VITAMIN_A: 27,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Leche entera',
    description: 'USDA: Milk, whole, 3.25% milkfat, with added vitamin D.',
    categoryCode: 'DAIRY',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171265',
    nutrients: {
      ENERGY_KCAL: 61,
      PROTEIN: 3.15,
      CARBOHYDRATE: 4.8,
      FAT: 3.25,
      FIBER: 0,
      SUGAR: 5.05,
      SATURATED_FAT: 1.86,
      SODIUM: 43,
      CALCIUM: 113,
      IRON: 0.03,
      POTASSIUM: 132,
      MAGNESIUM: 10,
      VITAMIN_C: 0,
      VITAMIN_A: 46,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Queso semiduro genérico',
    description: "USDA: Cheese, cheddar (USDA's Food Distribution Program).",
    categoryCode: 'DAIRY',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '173414',
    nutrients: {
      ENERGY_KCAL: 403,
      PROTEIN: 22.9,
      CARBOHYDRATE: 3.37,
      FAT: 33.3,
      FIBER: 0,
      SUGAR: 0.48,
      SATURATED_FAT: 18.9,
      SODIUM: 653,
      CALCIUM: 710,
      IRON: 0.14,
      POTASSIUM: 76,
      MAGNESIUM: 27,
      VITAMIN_C: 0,
      VITAMIN_A: 337,
    },
    servings: [{ name: 'Rebanada', quantity: 1, unit: 'SLICE', equivalentGrams: 20 }],
    aliases: ['Queso en lonchas', 'Queso tajado'],
  },
  {
    ...globalFoodDefaults,
    name: 'Bebida cola sin azúcar',
    description: 'USDA FNDDS: Soft drink, cola, diet.',
    categoryCode: 'BEVERAGES',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_FNDDS_2021_2023',
    sourceReference: '2710542',
    nutrients: {
      ENERGY_KCAL: 2,
      PROTEIN: 0.11,
      CARBOHYDRATE: 0.29,
      FAT: 0.03,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 0,
      SODIUM: 8,
      CALCIUM: 3,
      IRON: 0.11,
      POTASSIUM: 8,
      MAGNESIUM: 1,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Agua',
    description: 'USDA: Water, bottled, generic.',
    categoryCode: 'BEVERAGES',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '173647',
    referenceUnit: ReferenceUnit.MILLILITER,
    nutrients: {
      ENERGY_KCAL: 0,
      PROTEIN: 0,
      CARBOHYDRATE: 0,
      FAT: 0,
      FIBER: 0,
      SUGAR: 0,
      SATURATED_FAT: 0,
      SODIUM: 4,
      CALCIUM: 0,
      IRON: 0,
      POTASSIUM: 0,
      MAGNESIUM: 0,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
    servings: [{ name: 'Taza', quantity: 1, unit: 'CUP', equivalentMilliliters: 240 }],
    aliases: ['Agua potable'],
  },
  {
    ...globalFoodDefaults,
    name: 'Harina de maíz para arepas',
    description:
      'Alimento local de demostración; valores aproximados para harina precocida de maíz.',
    categoryCode: 'CEREALS',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'LOCAL_SEED',
    sourceReference: 'LOCAL_SEED:AREPA_CORN_FLOUR',
    confidenceLevel: ConfidenceLevel.USER_PROVIDED,
    nutrients: {
      ENERGY_KCAL: 360,
      PROTEIN: 7,
      CARBOHYDRATE: 79,
      FAT: 2.5,
      FIBER: 5,
      SUGAR: 1,
      SATURATED_FAT: 0.4,
      SODIUM: 20,
      CALCIUM: 20,
      IRON: 1.5,
      POTASSIUM: 240,
      MAGNESIUM: 30,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
    servings: [{ name: 'Taza', quantity: 1, unit: 'CUP', equivalentGrams: 120 }],
    aliases: ['Harina de arepa', 'Harina de maíz precocida'],
  },
  {
    ...globalFoodDefaults,
    name: 'Jamón cocido',
    description: 'USDA: Ham, sliced, regular (approximately 11% fat), cooked.',
    categoryCode: 'MEAT',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '167094',
    nutrients: {
      ENERGY_KCAL: 145,
      PROTEIN: 20.9,
      CARBOHYDRATE: 1.5,
      FAT: 5.5,
      FIBER: 0,
      SUGAR: 1.2,
      SATURATED_FAT: 1.8,
      SODIUM: 1200,
      CALCIUM: 8,
      IRON: 0.9,
      POTASSIUM: 287,
      MAGNESIUM: 20,
      VITAMIN_C: 0,
      VITAMIN_A: 0,
    },
    servings: [{ name: 'Rebanada', quantity: 1, unit: 'SLICE', equivalentGrams: 20 }],
    aliases: ['Jamón', 'Jamón en lonchas'],
  },
  {
    ...globalFoodDefaults,
    name: 'Lechuga romana',
    description: 'USDA: Lettuce, cos or romaine, raw.',
    categoryCode: 'VEGETABLES',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '169247',
    nutrients: {
      ENERGY_KCAL: 17,
      PROTEIN: 1.23,
      CARBOHYDRATE: 3.29,
      FAT: 0.3,
      FIBER: 2.1,
      SUGAR: 1.19,
      SATURATED_FAT: 0.039,
      SODIUM: 8,
      CALCIUM: 33,
      IRON: 0.97,
      POTASSIUM: 247,
      MAGNESIUM: 14,
      VITAMIN_C: 4,
      VITAMIN_A: 436,
    },
    aliases: ['Lechuga'],
  },
  {
    ...globalFoodDefaults,
    name: 'Aguacate',
    description: 'USDA: Avocados, raw, all commercial varieties.',
    categoryCode: 'FRUITS',
    preparationState: PreparationState.READY_TO_EAT,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '171705',
    nutrients: {
      ENERGY_KCAL: 160,
      PROTEIN: 2,
      CARBOHYDRATE: 8.53,
      FAT: 14.7,
      FIBER: 6.7,
      SUGAR: 0.66,
      SATURATED_FAT: 2.13,
      SODIUM: 7,
      CALCIUM: 12,
      IRON: 0.55,
      POTASSIUM: 485,
      MAGNESIUM: 29,
      VITAMIN_C: 10,
      VITAMIN_A: 7,
    },
    servings: [{ name: 'Medio aguacate', quantity: 0.5, unit: 'UNIT', equivalentGrams: 68 }],
    aliases: ['Palta'],
  },
  {
    ...globalFoodDefaults,
    name: 'Huevo revuelto',
    description:
      'Preparación local de demostración; valor aproximado, no es una medición de laboratorio.',
    categoryCode: 'EGGS',
    preparationState: PreparationState.COOKED,
    source: 'LOCAL_SEED',
    sourceReference: 'LOCAL_SEED:SCRAMBLED_EGG',
    confidenceLevel: ConfidenceLevel.MEDIUM,
    nutrients: {
      ENERGY_KCAL: 166,
      PROTEIN: 10.3,
      CARBOHYDRATE: 1.6,
      FAT: 12.3,
      FIBER: 0,
      SUGAR: 1.1,
      SATURATED_FAT: 3.8,
      SODIUM: 140,
      CALCIUM: 50,
      IRON: 1.5,
      POTASSIUM: 130,
      MAGNESIUM: 10,
      VITAMIN_C: 0,
      VITAMIN_A: 170,
    },
    servings: [{ name: 'Porción', quantity: 1, unit: 'SERVING', equivalentGrams: 100 }],
    aliases: ['Huevos revueltos'],
  },
  {
    ...globalFoodDefaults,
    name: 'Banana',
    description: 'USDA: Bananas, raw.',
    categoryCode: 'FRUITS',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '173944',
    nutrients: {
      ENERGY_KCAL: 89,
      PROTEIN: 1.09,
      CARBOHYDRATE: 22.8,
      FAT: 0.33,
      FIBER: 2.6,
      SUGAR: 12.2,
      SATURATED_FAT: 0.112,
      SODIUM: 1,
      CALCIUM: 5,
      IRON: 0.26,
      POTASSIUM: 358,
      MAGNESIUM: 27,
      VITAMIN_C: 8.7,
      VITAMIN_A: 3,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Cebolla',
    description: 'USDA: Onions, raw.',
    categoryCode: 'VEGETABLES',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '170000',
    nutrients: {
      ENERGY_KCAL: 40,
      PROTEIN: 1.1,
      CARBOHYDRATE: 9.34,
      FAT: 0.1,
      FIBER: 1.7,
      SUGAR: 4.24,
      SATURATED_FAT: 0.042,
      SODIUM: 4,
      CALCIUM: 23,
      IRON: 0.21,
      POTASSIUM: 146,
      MAGNESIUM: 10,
      VITAMIN_C: 7.4,
      VITAMIN_A: 0,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Tomate',
    description: 'USDA: Tomatoes, red, ripe, raw, year round average.',
    categoryCode: 'VEGETABLES',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '170457',
    nutrients: {
      ENERGY_KCAL: 18,
      PROTEIN: 0.88,
      CARBOHYDRATE: 3.89,
      FAT: 0.2,
      FIBER: 1.2,
      SUGAR: 2.63,
      SATURATED_FAT: 0.028,
      SODIUM: 5,
      CALCIUM: 10,
      IRON: 0.27,
      POTASSIUM: 237,
      MAGNESIUM: 11,
      VITAMIN_C: 13.7,
      VITAMIN_A: 42,
    },
  },
  {
    ...globalFoodDefaults,
    name: 'Ajo',
    description: 'USDA: Garlic, raw.',
    categoryCode: 'CONDIMENTS',
    preparationState: PreparationState.RAW,
    source: 'USDA_FDC_SR_LEGACY',
    sourceReference: '169230',
    nutrients: {
      ENERGY_KCAL: 149,
      PROTEIN: 6.36,
      CARBOHYDRATE: 33.1,
      FAT: 0.5,
      FIBER: 2.1,
      SUGAR: 1,
      SATURATED_FAT: 0.089,
      SODIUM: 17,
      CALCIUM: 181,
      IRON: 1.7,
      POTASSIUM: 401,
      MAGNESIUM: 25,
      VITAMIN_C: 31.2,
      VITAMIN_A: 0,
    },
  },
];
